import { defineActor, getActor, type ActorSpec } from './actorRegistry'

export const CORE_ACTORS: ActorSpec[] = [
  {
    id: 'lowPolyNightSky',
    domain: 'webgl',
    layer: 'webgl.nightSky',
    lifecycle: { mount: 'always', dispose: 'auto' },
    timing: { clocks: ['elapsedTime'], ranges: [] },
    consumes: ['clock.elapsedTime', 'camera'],
    debug: { label: 'Low-poly Night Sky' },
  },
  {
    id: 'sceneBackground',
    domain: 'webgl',
    layer: 'webgl.oceanLines',
    lifecycle: { mount: 'always', dispose: 'none' },
    timing: { clocks: ['scroll'], ranges: ['miniatureShrink', 'act2ThemeReveal'] },
    frame: { phase: 'timeline', before: ['beam', 'waves', 'planets'] },
    consumes: ['scroll.sp', 'theme.sceneBlend'],
    produces: ['scene.background', 'scene.fog'],
    debug: { label: 'Scene Background', inspect: ['miniatureShrink', 'themeReveal', 'fogDensity'] },
  },
  {
    id: 'beam',
    domain: 'webgl',
    layer: 'webgl.lightBeam',
    lifecycle: { mount: 'always', dispose: 'auto' },
    timing: { clocks: ['scroll', 'elapsedTime'], ranges: ['miniatureShrink'] },
    frame: {
      phase: 'webgl.produce',
      before: ['waves'],
      skipWhenUnchanged: ['scroll', 'elapsedTime'],
    },
    consumes: ['scroll.sp', 'clock.elapsedTime'],
    produces: ['anchor.beam.worldOrigin', 'anchor.beam.worldDirection'],
    effects: { cancelOnUnmount: true },
  },
  {
    id: 'waves',
    domain: 'webgl',
    layer: 'webgl.oceanLines',
    lifecycle: { mount: 'always', activeWhen: 'timeline.wavesAct3Fade.progress < 1', dispose: 'auto' },
    timing: { clocks: ['scroll', 'elapsedTime'], ranges: ['wavesAct3Fade'] },
    frame: {
      phase: 'webgl.mutate',
      after: ['beam'],
      before: ['planets'],
      skipWhenUnchanged: ['scroll', 'elapsedTime'],
    },
    consumes: [
      'scroll.sp',
      'clock.elapsedTime',
      'anchor.beam.worldOrigin',
      'anchor.beam.worldDirection',
    ],
  },
  {
    id: 'planets',
    domain: 'webgl',
    layer: 'webgl.planets',
    lifecycle: { mount: 'always', activeWhen: 'timeline.planetVisible.active', dispose: 'auto' },
    timing: { clocks: ['scroll', 'elapsedTime', 'delta'], ranges: ['planetVisible', 'squareAct3Crossfade', 'act3OrbitResume', 'orbitGlow'] },
    frame: {
      phase: 'webgl.produce',
      after: ['waves'],
      before: ['projection', 'planetLabels'],
      skipWhenUnchanged: ['scroll', 'elapsedTime'],
    },
    consumes: ['scroll.sp', 'clock.elapsedTime', 'clock.delta', 'interaction.hoveredPlanet', 'interaction.focusedPlanet'],
    produces: [
      'anchor.planet.0.world',
      'anchor.planet.1.world',
      'anchor.planet.2.world',
      'anchor.planet.0.screenRadius',
      'anchor.planet.1.screenRadius',
      'anchor.planet.2.screenRadius',
      'realtime.planetData',
    ],
    interaction: { pointer: 'none', hoverSource: 'screen' },
  },
  {
    id: 'centralStar',
    domain: 'webgl',
    layer: 'webgl.star',
    lifecycle: { mount: 'always', activeWhen: 'timeline.planetVisible.active', dispose: 'auto' },
    timing: { clocks: ['scroll', 'elapsedTime'], ranges: ['planetVisible', 'squareAct3Crossfade', 'orbitGlow'] },
    frame: { phase: 'webgl.mutate', after: ['planets'], skipWhenUnchanged: ['scroll', 'elapsedTime'] },
    consumes: ['scroll.sp', 'clock.elapsedTime'],
    produces: ['anchor.centralStar.world'],
  },
  {
    id: 'orbits',
    domain: 'webgl',
    layer: 'webgl.grid',
    lifecycle: { mount: 'always', activeWhen: 'timeline.squareAct3Crossfade.active || timeline.orbitLineReveal.active', dispose: 'auto' },
    timing: { clocks: ['scroll', 'delta'], ranges: ['squareAct3Crossfade', 'orbitLineReveal', 'act3OrbitResume'] },
    frame: { phase: 'webgl.mutate', after: ['centralStar'], skipWhenUnchanged: ['scroll'] },
    consumes: ['scroll.sp', 'clock.delta', 'theme.orbitColor'],
    produces: ['realtime.orbitAngles'],
  },
  {
    id: 'projection',
    domain: 'logic',
    lifecycle: { mount: 'always', dispose: 'none' },
    frame: { phase: 'projection', after: ['planets', 'centralStar'], before: ['planetLabels'] },
    consumes: ['anchor.planet.*.world', 'anchor.centralStar.world', 'camera.projection'],
    produces: ['anchor.planet.*.screen', 'anchor.centralStar.screen'],
  },
  {
    id: 'act3ContourProjection',
    domain: 'logic',
    lifecycle: { mount: 'always', activeWhen: 'timeline.squareTitleTyping.progress > 0 && timeline.squareAct3Crossfade.progress < 1', dispose: 'none' },
    timing: { clocks: ['scroll'], ranges: ['squareTitleTyping', 'squareAct3Crossfade'] },
    frame: { phase: 'projection', after: ['projection'], before: ['act2SquareContourTransition'] },
    consumes: ['anchor.planet.*.screen', 'anchor.planet.*.screenRadius', 'anchor.centralStar.screen', 'camera.projection', 'realtime.orbitAngles'],
    produces: ['anchor.act3Contour.target'],
  },
  {
    id: 'miniatureAbsorptionTrails',
    domain: 'webgl',
    layer: 'webgl.miniatureAbsorptionTrails',
    lifecycle: { mount: 'always', activeWhen: 'timeline.cubeAbsorptionTrails.active', dispose: 'auto' },
    timing: { clocks: ['scroll'], ranges: ['cubeAbsorptionTrails'] },
    frame: { phase: 'webgl.mutate', after: ['waves'], before: ['act2SquareContourTransition'], skipWhenUnchanged: ['scroll', 'anchor'] },
    consumes: ['scroll.sp', 'anchor.miniature.screenBounds', 'anchor.miniature.faceRect'],
    interaction: { pointer: 'none' },
  },
  {
    id: 'act2SquareContourTransition',
    domain: 'dom',
    layer: 'dom.act2SquareContourTransition',
    lifecycle: { mount: 'always', activeWhen: 'timeline.act2SquareTransition.active', dispose: 'auto' },
    timing: { clocks: ['scroll'], ranges: ['squareSeedShrink', 'squareBfsWave', 'squareCircleMorph', 'squareTitleTyping', 'squareContourZoom', 'squarePlanetFlights', 'squareOrbitFlights', 'squareTitleFade', 'squareAct3Crossfade'] },
    frame: { phase: 'dom.apply', after: ['act3ContourProjection'], skipWhenUnchanged: ['scroll', 'anchor'] },
    consumes: ['scroll.sp', 'anchor.miniature.faceRect', 'anchor.act3Contour.target'],
    interaction: { pointer: 'none' },
  },
  {
    id: 'seaCameraBob',
    domain: 'logic',
    lifecycle: { mount: 'always', activeWhen: 'timeline.act1OceanVoyage.active', dispose: 'none' },
    timing: { clocks: ['scroll', 'elapsedTime'], ranges: ['act1OceanVoyage'] },
    frame: { phase: 'camera', before: ['projection'] },
    consumes: ['scroll.sp', 'clock.elapsedTime'],
    produces: ['camera.position'],
    interaction: { pointer: 'none' },
  },
  {
    id: 'cameraFocus',
    domain: 'logic',
    lifecycle: { mount: 'always', dispose: 'none' },
    timing: { clocks: ['scroll', 'elapsedTime'], ranges: ['act3Shift'] },
    frame: { phase: 'camera', after: ['planets'], before: ['projection'] },
    consumes: ['scroll.sp', 'clock.elapsedTime', 'interaction.focusedPlanet', 'anchor.planet.*.world'],
    produces: ['camera.position', 'anchor.focusOverlay.geometry'],
    interaction: { pointer: 'none', blocksScrollWhenActive: true, blocksFastForwardWhenActive: true },
  },
  {
    id: 'brandTitle',
    domain: 'dom',
    layer: 'dom.brandTitle',
    lifecycle: { mount: 'always', dispose: 'none' },
    timing: { clocks: ['scroll'], ranges: ['brandTitle', 'act3Shift'] },
    frame: { phase: 'dom.apply', skipWhenUnchanged: ['scroll'] },
    consumes: ['scroll.sp', 'interaction.focusedPlanet', 'asset.lighthouseImage'],
    interaction: { pointer: 'none' },
  },
  {
    id: 'mainTerminal',
    domain: 'dom',
    layer: 'dom.mainTerminal',
    lifecycle: { mount: 'always', dispose: 'none' },
    timing: { clocks: ['signal'], sequences: ['mainTerminal'] },
    consumes: ['scroll.sp', 'theme.terminalVars'],
    produces: ['interaction.terminalMode', 'terminal.echoLines'],
    interaction: { pointer: 'auto', blocksScrollWhenActive: true, priority: 20 },
    effects: { ownsTimers: true, cancelOnUnmount: true },
  },
  {
    id: 'infoPanel',
    domain: 'dom',
    layer: 'dom.infoPanel',
    lifecycle: { mount: { sequence: 'act3.entry', phase: 'infoTyping' }, resetOn: ['act3.exit'], dispose: 'none' },
    timing: { clocks: ['signal'], sequences: ['act3.entry'] },
    consumes: ['realtime.planetData', 'realtime.cameraData', 'realtime.debrisCount'],
    produces: ['signal.act3.infoWelcomeDone'],
    interaction: { pointer: 'auto', priority: 10 },
    effects: { ownsTimers: true, cancelOnReset: true, cancelOnUnmount: true },
  },
  {
    id: 'planetLabels',
    domain: 'dom',
    layer: 'dom.planetLabels',
    lifecycle: { mount: { sequence: 'act3.entry', phase: 'labelsReveal' }, resetOn: ['act3.exit'], dispose: 'none' },
    timing: { clocks: ['signal'], sequences: ['act3.entry', 'labelReveal'] },
    frame: { phase: 'layout.solve', after: ['projection'], before: ['focusOverlay'] },
    consumes: [
      'anchor.planet.*.screen',
      'anchor.planet.*.screenRadius',
      'anchor.centralStar.screen',
      'sequence.act3.entry.phase',
    ],
    produces: ['layout.label.*.box', 'signal.label.*.typingDone', 'signal.label.*.shrinkDone'],
    layout: {
      solver: 'pbd',
      coordinateSpace: 'cssPx',
      measure: true,
      clampToViewport: true,
      avoid: ['anchor.centralStar.screen', 'layout.label.*.box'],
      output: 'layout.label.*.box',
    },
    interaction: { pointer: 'autoWhenVisible', capturesFocus: true, priority: 30 },
    effects: { ownsTimers: true, ownsRaf: true, cancelOnReset: true, cancelOnUnmount: true },
  },
  {
    id: 'focusOverlay',
    domain: 'svg',
    layer: 'svg.focusOverlay',
    lifecycle: { mount: 'always', activeWhen: 'interaction.focusedPlanet >= 0', dispose: 'none' },
    frame: { phase: 'dom.apply', after: ['cameraFocus', 'projection'] },
    consumes: ['anchor.focusOverlay.geometry'],
    interaction: { pointer: 'none' },
  },
  {
    id: 'lusionAtmosphereOverlay',
    domain: 'dom',
    layer: 'dom.lusionAtmosphere',
    lifecycle: { mount: 'always', activeWhen: 'timeline.act3Shift.active', dispose: 'auto' },
    timing: { clocks: ['scroll', 'elapsedTime', 'delta'], ranges: ['act3Shift'] },
    frame: { phase: 'dom.apply', after: ['projection'] },
    consumes: [
      'scroll.sp',
      'clock.elapsedTime',
      'clock.delta',
      'theme.dayNight',
      'anchor.centralStar.screen',
      'anchor.planet.*.screen',
      'anchor.planet.*.screenRadius',
    ],
    produces: ['realtime.tyndallLightShafts'],
    interaction: { pointer: 'none' },
    effects: { ownsRaf: true, cancelOnUnmount: true },
  },
]

export function registerCoreActors(): void {
  for (const spec of CORE_ACTORS) {
    if (!getActor(spec.id)) defineActor(spec)
  }
}
